<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f3a1d581-fe32-48cb-8f28-9bff478d1600</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskSync.Application\TaskSync.Application.csproj" />
    <ProjectReference Include="..\TaskSync.Persistence\TaskSync.Persistence.csproj" />
    <ProjectReference Include="..\TaskSync.SharedKernel\TaskSync.SharedKernel.csproj" />
  </ItemGroup>

</Project>
